import {
  AdminLogo,
  DarKLogoBlack,
  DarkCheck,
  DarkDashboard,
  DarkInbox,
  DarkInsight,
  DarkLogo,
  DarkMiniLogo,
  DarkProduct,
  DarkTeam,
  LightBell,
  LightCheck,
  LightDashboard,
  LightFacebook,
  LightGoogle,
  LightInbox,
  LightInfo,
  LightInsight,
  LightIos,
  LightLock,
  LightLogoWhite,
  LightMiniLogo,
  LightProduct,
  LightSearch,
  LightTeam,
  LightToggle,
} from '../icons/index';

export const lightTheme = {
  brandColor: {
    primary: '#7367F0',
    secondary: '#453E90',
    lighter: '#ABA4F6',
    subtle: '#E3E1FC',
    bgColor: '#F4F3F5',
  },
  statusColor: {
    error: '#FF3B3B',
    warning: '#FFCC00',
    info: '#0063F7',
    success: '#06C270',
  },
  darkColor: {
    dark1: '#4E4E4E',
    dark2: '#7A7A7A',
    dark3: '#A7A7A7',
    dark4: '#D3D3D3',
  },
  customColor: {
    primary: '#fff',
    secondary: '#000',
    toggleBg: '#E0E0E5',
    linkText: '#8D8D8D',
    headText: '#070707',
    greyText: '#eee',
    purpleText: '#171530',
    greyBorder: '#ebebeb',
    notifyEvenBg: '#fcf9e1',
    notifyEvenText: '#BCB155',
    notifyOddBg: ' #e3e1fc',
    notifyOddText: '#928DCC',
    notifyUnreadBg: '#F3E1FC',
    notifyUnreadText: '#B490C7',
    blueText: '#2D313A',
    purpleLight: '#C7C2F9',
    pinkBg: '#DA68CE',
    sidebarToggleBg: '#5C52C0',
    grapStats: '#8F85F3',
  },
  transparency: {
    brandColor: {
      subtle: '227, 225, 252',
    },
    darkColor: {
      dark3: '167, 167, 167',
      dark4: '211, 211, 211',
    },
    customColor: {
      sidebarToggleBg: '92,82,192',
    },
  },
  fontSize: {
    semiSmall: '12px',
    small: '14px',
    normal: '16px',
    medium: '18px',
    large: '20px',
    font22: '22px',
    font24: '24px',
    font30: '30px',
    font34: '34px',
  },
  toggle: <LightToggle />,
  logo: <AdminLogo />,
  check: <LightCheck />,
  google: <LightGoogle />,
  facebook: <LightFacebook />,
  ios: <LightIos />,
  lock: <LightLock />,
  logoWhite: <LightLogoWhite />,
  dashboard: <LightDashboard />,
  product: <LightProduct />,
  insight: <LightInsight />,
  team: <LightTeam />,
  inbox: <LightInbox />,
  search: <LightSearch />,
  bell: <LightBell />,
  info: <LightInfo />,
  miniLogo: <LightMiniLogo />,
};

export const darkTheme = {
  brandColor: {
    primary: '#7367F0',
    secondary: '#453E90',
    lighter: '#ABA4F6',
    subtle: '#E3E1FC',
    bgColor: '#F4F3F5',
  },
  statusColor: {
    error: '#FF3B3B',
    warning: '#FFCC00',
    info: '#0063F7',
    success: '#06C270',
  },
  darkColor: {
    dark1: '#4E4E4E',
    dark2: '#7A7A7A',
    dark3: '#A7A7A7',
    dark4: '#D3D3D3',
  },
  customColor: {
    primary: '#000',
    secondary: '#fff',
    toggleBg: '#E0E0E5',
    linkText: '#8D8D8D',
    headText: '#070707',
    greyText: '#eee',
    purpleText: '#171530',
    greyBorder: '#ebebeb',
    notifyEvenBg: '#fcf9e1',
    notifyEvenText: '#BCB155',
    notifyOddBg: ' #e3e1fc',
    notifyOddText: '#928DCC',
    notifyUnreadBg: '#F3E1FC',
    notifyUnreadText: '#B490C7',
    blueText: '#2D313A',
    purpleLight: '#C7C2F9',
    pinkBg: '#DA68CE',
    sidebarToggleBg: '#5C52C0',
    grapStats: '#8F85F3',
  },
  transparency: {
    brandColor: {
      subtle: '227, 225, 252',
    },
    darkColor: {
      dark3: '#A7A7A7',
    },
    customColor: {
      sidebarToggleBg: '92,82,192',
    },
  },
  fontSize: {
    semiSmall: '12px',
    small: '14px',
    normal: '16px',
    medium: '18px',
    large: '20px',
    font22: '22px',
    font24: '24px',
    font30: '30px',
    font34: '34px',
  },
  toggle: <LightToggle />,
  logo: <DarkLogo />,
  check: <DarkCheck />,
  google: <LightGoogle />,
  facebook: <LightFacebook />,
  ios: <LightIos />,
  lock: <LightLock />,
  logoWhite: <DarKLogoBlack />,
  dashboard: <DarkDashboard />,
  product: <DarkProduct />,
  insight: <DarkInsight />,
  team: <DarkTeam />,
  inbox: <DarkInbox />,
  search: <LightSearch />,
  bell: <LightBell />,
  info: <LightInfo />,
  miniLogo: <DarkMiniLogo />,
};
